### ISSUE TITLE
RabbitMQ中文文档站最近一直访问不了，请看看是什么原因？

### ISSUE THREAD

**Issue by bingohuang** [mr-ping/RabbitMQ_into_Chinese#2]
RabbitMQ中文文档站（ http://rabbitmq.mr-ping.com/ ）最近一直访问不了，请看看是什么原因？
感谢翻译贡献！

**Comment by mr-ping** [comment]
之前因为域名问题导致服务停止了不少时间，现在域名已经取回，服务重启 ^^

**Comment by 1228857713** [comment]
域名又丢了嘛

**Comment by bingohuang** [comment]
又访问不了了，我close了
